/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Container;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author hp
 */
public class JF_Menu extends javax.swing.JFrame {

    /**
     * Creates new form JF_Menu
     */

    public JF_Menu() {
        initComponents();
    }

    public JMenuItem getJmenuInscripcion() {
        return JmenuInscripcion;
    }

    public void setJmenuInscripcion(JMenuItem JmenuInscripcion) {
        this.JmenuInscripcion = JmenuInscripcion;
    }

    public JMenuItem getjMenuCarreras() {
        return jMenuCarreras;
    }

    public void setjMenuCarreras(JMenuItem jMenuCarreras) {
        this.jMenuCarreras = jMenuCarreras;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuItem getjMenu1Alumno() {
        return jMenu1Alumno;
    }

    public void setjMenu1Alumno(JMenuItem jMenu1Alumno) {
        this.jMenu1Alumno = jMenu1Alumno;
    }

    public JMenuItem getjMenu2Profesor() {
        return jMenu2Profesor;
    }

    public void setjMenu2Profesor(JMenuItem jMenu2Profesor) {
        this.jMenu2Profesor = jMenu2Profesor;
    }

    public JMenuItem getjMenu3Materia() {
        return jMenu3Materia;
    }

    public void setjMenu3Materia(JMenuItem jMenu3Materia) {
        this.jMenu3Materia = jMenu3Materia;
    }

    public JMenuItem getjMenu4Notas() {
        return jMenu4Notas;
    }

    public void setjMenu4Notas(JMenuItem jMenu4Notas) {
        this.jMenu4Notas = jMenu4Notas;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu1Alumno = new javax.swing.JMenuItem();
        jMenu2Profesor = new javax.swing.JMenuItem();
        jMenu3Materia = new javax.swing.JMenuItem();
        JmenuInscripcion = new javax.swing.JMenuItem();
        jMenuCarreras = new javax.swing.JMenuItem();
        jMenu4Notas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        jMenu1Alumno.setText("Alumno");
        jMenu1.add(jMenu1Alumno);

        jMenu2Profesor.setText("Profesor");
        jMenu1.add(jMenu2Profesor);

        jMenu3Materia.setText("Materia");
        jMenu1.add(jMenu3Materia);

        JmenuInscripcion.setText("Inscripcion");
        jMenu1.add(JmenuInscripcion);

        jMenuCarreras.setText("Carreras");
        jMenu1.add(jMenuCarreras);

        jMenu4Notas.setText("Cursado");
        jMenu1.add(jMenu4Notas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmenuInscripcion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenu1Alumno;
    private javax.swing.JMenuItem jMenu2Profesor;
    private javax.swing.JMenuItem jMenu3Materia;
    private javax.swing.JMenuItem jMenu4Notas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCarreras;
    // End of variables declaration//GEN-END:variables
}
